#
# pppdump Makefile for SVR4 systems
# $Id: //WIFI_SOC/MP/SDK_4_3_0_0/RT288x_SDK/source/user/ppp-2.4.2/pppdump/Makefile.sol2#1 $
#

include ../Makedefs.com

CFLAGS= $(COPTS) -I../include/net
OBJS = pppdump.o bsd-comp.o deflate.o zlib.o

all:	pppdump

pppdump: $(OBJS)
	$(CC) -o pppdump $(OBJS)

clean:
	rm -f $(OBJS) pppdump *~

install:
	$(INSTALL) -f $(BINDIR) pppdump
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppdump.8
