#
# pppstats makefile
# $Id: //WIFI_SOC/MP/SDK_4_3_0_0/RT288x_SDK/source/user/ppp-2.4.2/pppdump/Makefile.sunos4#1 $
#

include ../sunos4/Makedefs

OBJS = pppdump.o bsd-comp.o deflate.o zlib.o
CFLAGS = $(COPTS) -I../include/net

all:	pppdump

pppdump: $(OBJS)
	$(CC) -o pppdump $(OBJS)

clean:
	rm -f pppdump $(OBJS) *~

install: pppdump
	$(INSTALL) -c pppdump $(BINDIR)/pppdump
	$(INSTALL) -c -m 444 pppdump.8 $(MANDIR)/man8/pppdump.8
