# $Id: //WIFI_SOC/MP/SDK_4_3_0_0/RT288x_SDK/source/linux-2.6.21.x/arch/m68k/sun3/prom/Makefile#1 $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
