# Automatically generated by configure - do not modify!
VERSION=0.2.3
PREFIX=/usr/local
prefix=$(DESTDIR)$(PREFIX)
libdir=$(DESTDIR)$(PREFIX)/lib
includedir=$(DESTDIR)$(PREFIX)/include
MAKE=make
#CC=gcc
#AR=ar
RANLIB=ranlib
BUILD_STATIC=yes
BUILD_SHARED=yes
LN=ln
#STRIP=strip
INSTALLSTRIP=-s
EXTRALIBS=
OPTFLAGS= -W -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O3
LDFLAGS=
INSTALL=/usr/bin/install -c
DEBUG=no
