/*
** Copyright (c) 2009-2010 by Silicon Laboratories
**
** $Id: //WIFI_SOC/MP/SDK_4_3_0_0/RT288x_SDK/source/linux-2.6.36MT.x/drivers/char/pcm/pcm_slic/proslic_api/src/si_voice_version.c#1 $
**
** si_voice_version.c
** ProSLIC API Version
**
** Author(s): 
** cdp
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *SiVoiceAPIVersion = "5.2.1";
